### ISSUE TITLE
Get YAML Error from sops output

### ISSUE THREAD

**Issue by pavelzw** [nikaro/sopsy#73]
https://github.com/nikaro/sopsy/blob/e0a9c0ad165cdca84a1c1492504cf1ecc00dbc49/tests/test_sopsy.py#L349

You are mocking `b'{"hello": "world"}'` to be the output of SOPS. In my testing, i found that `b'{\n\t"hello": "world"\n}'` seems to be the actual output of sops (i'm using sops 3.9.1 on a M1 MacBook).

This unfortunately raises an error in

https://github.com/nikaro/sopsy/blob/e0a9c0ad165cdca84a1c1492504cf1ecc00dbc49/src/sopsy/utils.py#L66

```
Traceback (most recent call last):
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/sopsy/utils.py", line 66, in get_dict
    out = yaml.safe_load(data)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/parser.py", line 142, in parse_implicit_document_start
    if not self.check_token(DirectiveToken, DocumentStartToken,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/pavel/Projects/pydantic-settings-sops/.pixi/envs/default/lib/python3.12/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<byte string>", line 2, column 1:
    	"foobar": "foo"

```

**Comment by nikaro** [comment]
I'am also using sops 3.9.1 on a M1 and i don't have this issue. Tests are passing from python 3.9 to 3.12.

How do you get this error? While running test or with actual code? Can you provide a reproduction case?

**Comment by pavelzw** [comment]
Is the failing CI in https://github.com/pavelzw/pydantic-settings-sops/pull/3 enough for you?

You should be able to reproduce it locally by doing the following

```bash
# checkout PR
brew install pixi
pixi run postinstall
pixi run test
```

otherwise i can try to create a smaller reproducer

**Comment by nikaro** [comment]
Weird, i still do not reproduce it with your steps:
```
⏺ ~/D/g/p/pydantic-settings-sops | main✓ > set -x SOPS_AGE_KEY (grep AGE-SECRET tests/resources/key.txt)
⏺ ~/D/g/p/pydantic-settings-sops | main✓ > pixi run test
✨ Pixi task (test in default): pytest
======================================================= test session starts =======================================================
platform darwin -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/nicolas/Developer/github.com/pavelzw/pydantic-settings-sops
configfile: pyproject.toml
testpaths: tests
plugins: cov-5.0.0
collected 1 item

tests/test_sops.py .                                                                                                        [100%]

======================================================== warnings summary =========================================================
tests/test_sops.py:20
  /Users/nicolas/Developer/github.com/pavelzw/pydantic-settings-sops/tests/test_sops.py:20: PytestCollectionWarning: cannot collect test class 'TestSettings' because it has a __init__ constructor (from: tests/test_sops.py)
    class TestSettings(BaseSettings):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================== 1 passed, 1 warning in 0.20s ===================================================
```

I will continue to investigate, maybe trying to remove mocking for sops commands and let sops do the actual job to ensure it is correct (it may require a bit more setup though...). But if you could provide a small reproducer it would be nice.

**Comment by nikaro** [comment]
Ok now i can reproduce. PyYAML cannot load (pretty) JSON it seems. I will try to fix it this weekend.

**Comment by nikaro** [comment]
This is fixed and released in https://github.com/nikaro/sopsy/releases/tag/1.0.1

Thanks for reporting it.
